version : '3'
services:
  web:
   build:
    context: .
    dockerfile: Dockerfile.dev
   ports:
     - "4002:3000"
   volumes:
     - /app/node_modules
     - /Docker/reactprod/frontend/:/app
  tests:
    build:
     context: .
     dockerfile: Dockerfile.dev
    volumes:
     - /app/node_modules
     - /Docker/reactprod/frontend/:/app
    command: ["npm", "run", "test"]